-- Sample courses for testing
-- Run this in your Supabase SQL editor

-- Insert sample courses
INSERT INTO courses (
  title,
  description,
  short_description,
  category,
  level,
  difficulty_level,
  duration_hours,
  thumbnail_url,
  video_url,
  is_published,
  is_free,
  monthly_price,
  yearly_price,
  currency,
  category_restrictions,
  created_at,
  updated_at
) VALUES 
(
  'Introduction à la Programmation',
  'Ce cours vous initie aux concepts fondamentaux de la programmation. Vous apprendrez les bases de la logique algorithmique, les structures de données essentielles, et les principes de développement de logiciels.',
  'Apprenez les bases de la programmation',
  'Développement Web',
  'Bac',
  'Débutant',
  20,
  'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  true,
  true,
  0,
  0,
  'TND',
  ARRAY[1, 2, 3, 4, 5],
  NOW(),
  NOW()
),
(
  'Développement Web Avancé',
  'Maîtrisez les technologies web modernes avec React, Node.js et les bases de données. Ce cours couvre le développement full-stack et les meilleures pratiques de l\'industrie.',
  'Développement web full-stack moderne',
  'Développement Web',
  'Université',
  'Intermédiaire',
  40,
  'https://images.unsplash.com/photo-1461749280684-dccba6e2f0d6?w=500',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  true,
  false,
  25,
  200,
  'TND',
  ARRAY[2, 4],
  NOW(),
  NOW()
),
(
  'Intelligence Artificielle pour Débutants',
  'Découvrez l\'IA et le machine learning. Apprenez à utiliser Python pour créer des modèles d\'apprentissage automatique et comprendre les concepts de l\'intelligence artificielle.',
  'Introduction à l\'IA et au machine learning',
  'Intelligence Artificielle',
  'Université',
  'Débutant',
  30,
  'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=500',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  true,
  false,
  30,
  250,
  'TND',
  ARRAY[2, 4, 7],
  NOW(),
  NOW()
),
(
  'Mathématiques pour le Bac',
  'Cours complet de mathématiques pour préparer le baccalauréat. Algèbre, géométrie, probabilités et statistiques avec exercices pratiques.',
  'Préparation complète aux mathématiques du bac',
  'Mathématiques',
  'Bac',
  'Intermédiaire',
  25,
  'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=500',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  true,
  true,
  0,
  0,
  'TND',
  ARRAY[1, 3, 4],
  NOW(),
  NOW()
),
(
  'Bureautique Professionnelle',
  'Maîtrisez Microsoft Office (Word, Excel, PowerPoint) et les outils de productivité modernes pour améliorer votre efficacité professionnelle.',
  'Maîtrise des outils bureautiques',
  'Bureautique',
  'Professionnel',
  'Débutant',
  15,
  'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=500',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  true,
  false,
  20,
  150,
  'TND',
  ARRAY[5, 6],
  NOW(),
  NOW()
);

-- Insert user categories if they don't exist
INSERT INTO user_categories (id, name, description, created_at) VALUES 
(1, 'BAC Lettres', 'Baccalauréat Littéraire', NOW()),
(2, 'BAC Info', 'Baccalauréat Informatique', NOW()),
(3, 'BAC Éco', 'Baccalauréat Économique', NOW()),
(4, 'BAC Sciences', 'Baccalauréat Scientifique', NOW()),
(5, 'BAC Technique', 'Baccalauréat Technique', NOW()),
(6, 'Professionnel', 'Utilisateur Professionnel', NOW()),
(7, 'Étudiant Universitaire', 'Étudiant en Université', NOW()),
(8, 'Autre', 'Autre catégorie', NOW())
ON CONFLICT (id) DO NOTHING;
